<?php

namespace AppBundle\Repository;

/**
 * top100Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class top100Repository extends \Doctrine\ORM\EntityRepository
{
}
